"""empty message

Revision ID: 50a8cdb56c02
Revises: 
Create Date: 2024-03-13 14:24:24.908903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a8cdb56c02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_title', sa.String(length=100), nullable=True),
    sa.Column('property_description', sa.String(length=256), nullable=True),
    sa.Column('property_no_rooms', sa.Integer(), nullable=True),
    sa.Column('property_no_bathrooms', sa.Integer(), nullable=True),
    sa.Column('property_price', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('property_location', sa.String(length=101), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
