"""empty message

Revision ID: 840da620250d
Revises: 50a8cdb56c02
Create Date: 2024-03-13 20:11:20.141973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840da620250d'
down_revision = '50a8cdb56c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('property_location',
               existing_type=sa.VARCHAR(length=101),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('property_location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=101),
               existing_nullable=True)
        batch_op.drop_column('property_filename')

    # ### end Alembic commands ###
